services:
    hcg00e87l756en5xxidqg1gp-053956097588:
        image: 'hcg00e87l756en5xxidqg1gp:5cb24e425d21fdda155fa329b9fb870e16f6da3d'
        container_name: hcg00e87l756en5xxidqg1gp-053956097588
        restart: unless-stopped
        expose:
            - '3000'
        networks:
            coolify:
                aliases:
                    - hcg00e87l756en5xxidqg1gp-053956097588
        mem_limit: '0'
        memswap_limit: '0'
        mem_swappiness: 60
        mem_reservation: '0'
        cpus: 0.0
        cpu_shares: 1024
        env_file:
            - .env
        labels:
            - traefik.enable=true
            - traefik.http.middlewares.gzip.compress=true
            - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
            - traefik.http.routers.http-0-hcg00e87l756en5xxidqg1gp.entryPoints=http
            - traefik.http.routers.http-0-hcg00e87l756en5xxidqg1gp.middlewares=gzip
            - 'traefik.http.routers.http-0-hcg00e87l756en5xxidqg1gp.rule=Host(`hcg00e87l756en5xxidqg1gp.163.227.239.135.sslip.io`) && PathPrefix(`/`)'
            - traefik.http.routers.http-0-hcg00e87l756en5xxidqg1gp.service=http-0-hcg00e87l756en5xxidqg1gp
            - traefik.http.routers.http-1-hcg00e87l756en5xxidqg1gp.entryPoints=http
            - traefik.http.routers.http-1-hcg00e87l756en5xxidqg1gp.middlewares=redirect-to-https
            - 'traefik.http.routers.http-1-hcg00e87l756en5xxidqg1gp.rule=Host(`burmesebazaar.com`) && PathPrefix(`/`)'
            - traefik.http.routers.http-1-hcg00e87l756en5xxidqg1gp.service=http-1-hcg00e87l756en5xxidqg1gp
            - traefik.http.routers.http-2-hcg00e87l756en5xxidqg1gp.entryPoints=http
            - traefik.http.routers.http-2-hcg00e87l756en5xxidqg1gp.middlewares=redirect-to-https
            - 'traefik.http.routers.http-2-hcg00e87l756en5xxidqg1gp.rule=Host(`www.burmesebazaar.com`) && PathPrefix(`/`)'
            - traefik.http.routers.http-2-hcg00e87l756en5xxidqg1gp.service=http-2-hcg00e87l756en5xxidqg1gp
            - traefik.http.routers.https-1-hcg00e87l756en5xxidqg1gp.entryPoints=https
            - traefik.http.routers.https-1-hcg00e87l756en5xxidqg1gp.middlewares=gzip
            - 'traefik.http.routers.https-1-hcg00e87l756en5xxidqg1gp.rule=Host(`burmesebazaar.com`) && PathPrefix(`/`)'
            - traefik.http.routers.https-1-hcg00e87l756en5xxidqg1gp.service=https-1-hcg00e87l756en5xxidqg1gp
            - traefik.http.routers.https-1-hcg00e87l756en5xxidqg1gp.tls.certresolver=letsencrypt
            - traefik.http.routers.https-1-hcg00e87l756en5xxidqg1gp.tls=true
            - traefik.http.routers.https-2-hcg00e87l756en5xxidqg1gp.entryPoints=https
            - traefik.http.routers.https-2-hcg00e87l756en5xxidqg1gp.middlewares=gzip
            - 'traefik.http.routers.https-2-hcg00e87l756en5xxidqg1gp.rule=Host(`www.burmesebazaar.com`) && PathPrefix(`/`)'
            - traefik.http.routers.https-2-hcg00e87l756en5xxidqg1gp.service=https-2-hcg00e87l756en5xxidqg1gp
            - traefik.http.routers.https-2-hcg00e87l756en5xxidqg1gp.tls.certresolver=letsencrypt
            - traefik.http.routers.https-2-hcg00e87l756en5xxidqg1gp.tls=true
            - traefik.http.services.http-0-hcg00e87l756en5xxidqg1gp.loadbalancer.server.port=3000
            - traefik.http.services.http-1-hcg00e87l756en5xxidqg1gp.loadbalancer.server.port=3000
            - traefik.http.services.http-2-hcg00e87l756en5xxidqg1gp.loadbalancer.server.port=3000
            - traefik.http.services.https-1-hcg00e87l756en5xxidqg1gp.loadbalancer.server.port=3000
            - traefik.http.services.https-2-hcg00e87l756en5xxidqg1gp.loadbalancer.server.port=3000
            - 'caddy_0.encode=zstd gzip'
            - 'caddy_0.handle_path.0_reverse_proxy={{upstreams 3000}}'
            - 'caddy_0.handle_path=/*'
            - caddy_0.header=-Server
            - 'caddy_0.try_files={path} /index.html /index.php'
            - 'caddy_0=http://hcg00e87l756en5xxidqg1gp.163.227.239.135.sslip.io'
            - 'caddy_1.encode=zstd gzip'
            - 'caddy_1.handle_path.1_reverse_proxy={{upstreams 3000}}'
            - 'caddy_1.handle_path=/*'
            - caddy_1.header=-Server
            - 'caddy_1.try_files={path} /index.html /index.php'
            - 'caddy_1=https://burmesebazaar.com'
            - 'caddy_2.encode=zstd gzip'
            - 'caddy_2.handle_path.2_reverse_proxy={{upstreams 3000}}'
            - 'caddy_2.handle_path=/*'
            - caddy_2.header=-Server
            - 'caddy_2.try_files={path} /index.html /index.php'
            - 'caddy_2=https://www.burmesebazaar.com'
            - caddy_ingress_network=coolify
            - coolify.managed=true
            - coolify.version=4.0.0-beta.472
            - coolify.applicationId=1
            - coolify.type=application
            - coolify.name=hcg00e87l756en5xxidqg1gp
            - coolify.resourceName=burmesebazaarmain-hcg00e87l756en5xxidqg1gp
            - coolify.projectName=burmese-bazaar
            - coolify.serviceName=burmesebazaarmain-hcg00e87l756en5xxidqg1gp
            - coolify.environmentName=production
            - coolify.pullRequestId=0
networks:
    coolify:
        external: true
        name: coolify
        attachable: true
